name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  linux:
    name: Linux (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test

  macos:
    name: macOS (macos-latest)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test
